// ─────────────────────────────────────────────────────────────────────────────
// apply_apr2026_prices.cjs
// Generates:
//   A) supabase/migrations/20260401_apr2026_prices.sql   — DB upsert + deactivate
//   B) _out/bus_db_apr2026.js                            — BusCalculator DB array
//   C) _out/emi_vehicles_apr2026.js                      — EMI calculator array
//   D) _out/al_page_prices_apr2026.txt                   — Featured model prices
//
// Run: node scripts/apply_apr2026_prices.cjs
// ─────────────────────────────────────────────────────────────────────────────
const XLSX = require('xlsx')
const fs   = require('fs')
const path = require('path')

const EXCEL = 'D:/PTB/Website/parastrucks/pricelist/AL_Vehicle_Price_List_Apr2026.xlsx'
const OUT   = path.join(__dirname, '_out')

if (!fs.existsSync(OUT)) fs.mkdirSync(OUT)

// ── Read Excel ────────────────────────────────────────────────────────────────
const wb     = XLSX.readFile(EXCEL)
const ws     = wb.Sheets['Vehicle Price List']
const allRows = XLSX.utils.sheet_to_json(ws, { header: 1 }).slice(1)
  .filter(r => r[2] && r[5])
  .map(r => ({
    segment:    String(r[0] || '').trim(),
    sub_cat:    String(r[1] || '').trim(),
    cbn:        String(r[2] || '').trim(),
    desc:       String(r[3] || '').trim(),
    tyres:      String(r[4] || '').trim(),
    mrp:        parseInt(String(r[5]).replace(/[^0-9]/g, ''), 10),
  }))
  .filter(r => r.mrp > 0)

// ── Sep 2025 CBNs (from old seed) — needed to compute deactivation list ───────
// We read the old seed SQL to extract the full CBN list rather than hardcoding
const SEED_SQL = path.join(__dirname, '..', 'seed_vehicles.sql')
const oldCBNs  = new Set()
if (fs.existsSync(SEED_SQL)) {
  const txt = fs.readFileSync(SEED_SQL, 'utf8')
  for (const m of txt.matchAll(/'([A-Z0-9_]+)',\s*'[^']+',\s*'[^']+'/g)) {
    oldCBNs.add(m[1])
  }
}
const newCBNSet = new Set(allRows.map(r => r.cbn))
const deactivate = [...oldCBNs].filter(c => !newCBNSet.has(c))
process.stderr.write(`Old CBNs: ${oldCBNs.size} | Apr 2026: ${allRows.length} | To deactivate: ${deactivate.length}\n`)

// ── A) SQL Migration ──────────────────────────────────────────────────────────
const esc = s => String(s ?? '').replace(/'/g, "''").trim()

function priceCircular(seg) {
  if (seg === 'Bus – ICV' || seg === 'Bus – MCV') return 'PC-155 (Apr 2026)'
  return 'Apr 2026 Circular'
}

const sqlLines = [
  '-- Vehicle catalog update — Ashok Leyland Apr 2026 price list',
  '-- Source: AL_Vehicle_Price_List_Apr2026.xlsx (effective 2026-04-01)',
  '-- Generated by scripts/apply_apr2026_prices.cjs',
  '-- DO NOT manually edit — regenerate from script',
  '',
  '-- Upsert 797 active CBNs with Apr 2026 MRP values',
  'INSERT INTO public.vehicle_catalog',
  '  (cbn, description, segment, sub_category, tyres, mrp_incl_gst, gst_rate, price_circular, effective_date, is_active)',
  'VALUES',
]

const sqlValues = allRows.map(r => {
  const tyresVal = (r.tyres && r.tyres !== r.desc) ? `'${esc(r.tyres)}'` : 'NULL'
  return `  ('${esc(r.cbn)}', '${esc(r.desc)}', '${esc(r.segment)}', '${esc(r.sub_cat)}', ` +
         `${tyresVal}, ${r.mrp}, 18, '${priceCircular(r.segment)}', '2026-04-01', true)`
})
sqlLines.push(sqlValues.join(',\n'))
sqlLines.push('ON CONFLICT (cbn) DO UPDATE SET')
sqlLines.push('  description     = EXCLUDED.description,')
sqlLines.push('  segment         = EXCLUDED.segment,')
sqlLines.push('  sub_category    = EXCLUDED.sub_category,')
sqlLines.push('  tyres           = EXCLUDED.tyres,')
sqlLines.push('  mrp_incl_gst    = EXCLUDED.mrp_incl_gst,')
sqlLines.push('  price_circular  = EXCLUDED.price_circular,')
sqlLines.push('  effective_date  = EXCLUDED.effective_date,')
sqlLines.push('  is_active       = true;')
sqlLines.push('')

if (deactivate.length > 0) {
  sqlLines.push('-- Deactivate discontinued CBNs (not in Apr 2026 price list)')
  sqlLines.push(`UPDATE public.vehicle_catalog SET is_active = false`)
  sqlLines.push(`WHERE cbn IN (`)
  // chunk into rows of 5
  for (let i = 0; i < deactivate.length; i += 5) {
    const chunk = deactivate.slice(i, i + 5).map(c => `  '${c}'`).join(', ')
    sqlLines.push(chunk + (i + 5 < deactivate.length ? ',' : ''))
  }
  sqlLines.push(');')
  sqlLines.push('')
}

sqlLines.push(`-- ${allRows.length} rows upserted, ${deactivate.length} CBNs deactivated`)

const sqlPath = path.join(__dirname, '..', 'supabase', 'migrations', '20260401_apr2026_prices.sql')
fs.mkdirSync(path.dirname(sqlPath), { recursive: true })
fs.writeFileSync(sqlPath, sqlLines.join('\n') + '\n')
process.stderr.write(`✓ SQL → ${sqlPath}\n`)

// ── B) BusCalculator DB array ─────────────────────────────────────────────────
// Only cowl chassis (CC* prefix). Built buses (CB*, CE*) are excluded.
// For CBNs in the old curated list → preserve existing desc/fam/model/oll/fuel/ac
// For new cowl chassis → generate entry

// Curated map: CBN → {fam, model, desc, oll, fuel, ac}  (from old Sep 2025 DB array)
const CURATED = {
  'CCC20084D00011':{fam:'CCC',model:'Cheetah',oll:8.4,fuel:'D',ac:'NAC',desc:"ASHOK LEYLAND CH2008.4T6R — 4200mm WB · 'H' Series iGen6 6-cyl BS VI (197 HP) · 6-speed OD gearbox · Shackle suspension · Tilt & Telescopic steering · EB, ESC · 7 × 10R20-16PR Radial"},
  'CCC20102D00015':{fam:'CCC',model:'Cheetah',oll:10.2,fuel:'D',ac:'NAC',desc:"ASHOK LEYLAND CH2010.2T6R — 5334mm WB · 'H' Series iGen6 6-cyl BS VI (197 HP) · 6-speed OD gearbox · Shackle suspension · Tilt & Telescopic steering · EB, ESC · 7 × 10R20-16PR Radial"},
  'CCC20102D00014':{fam:'CCC',model:'Cheetah',oll:10.2,fuel:'D',ac:'NAC',desc:"ASHOK LEYLAND CH2010.2T6R — 5334mm WB · 'H' Series iGen6 6-cyl BS VI (197 HP) · 6-speed OD gearbox · Shackle suspension · Tilt & Telescopic steering · EB, ESC · 7 × 295/80 R22.5 TL"},
  'CCV20109D00029':{fam:'CCV',model:'Viking',oll:10.9,fuel:'D',ac:'NAC',desc:"ASHOK LEYLAND VK2010.9T6R — 5334mm WB · 'H' Series iGen6 6-cyl BS VI (197 HP) · 6-speed OD gearbox · Shackle suspension · Tilt & Telescopic steering · EB, ESC · 7 × 295/80 R22.5 TL"},
  'CCV20109D00030':{fam:'CCV',model:'Viking',oll:10.9,fuel:'D',ac:'NAC',desc:"ASHOK LEYLAND VK2010.9T6R — 5334mm WB · 'H' Series iGen6 6-cyl BS VI (197 HP) · 6-speed OD gearbox · Shackle suspension with Retarder · Tilt & Telescopic steering · EB, ESC · 7 × 295/80 R22.5 TL (M)"},
  'CCV20114D00105':{fam:'CCV',model:'Viking',oll:11.4,fuel:'D',ac:'NAC',desc:"ASHOK LEYLAND VK2011.4T6R — 5639mm WB · 'H' Series iGen6 6-cyl BS VI (197 HP) · 6-speed OD gearbox · Shackle suspension · Tilt & Telescopic steering · EB, ESC · 7 × 10R20-16PR Radial"},
  'CCV20114D00109':{fam:'CCV',model:'Viking',oll:11.4,fuel:'D',ac:'NAC',desc:"ASHOK LEYLAND VK2011.4T6R — 5639mm WB · 'H' Series iGen6 6-cyl BS VI (197 HP) · 6-speed OD gearbox · Shackle suspension · Tilt & Telescopic steering · EB, ESC · 7 × 295/80 R22.5 TL"},
  'CCV20114D00107':{fam:'CCV',model:'Viking',oll:11.4,fuel:'D',ac:'NAC',desc:"ASHOK LEYLAND VK2011.4T6R — 5639mm WB · 'H' Series iGen6 6-cyl BS VI (197 HP) · 6-speed OD gearbox · Rubber-ended suspension · Tilt & Telescopic steering · EB, ESC · 7 × 10R20-16PR Radial"},
  'CCV20114D00111':{fam:'CCV',model:'Viking',oll:11.4,fuel:'D',ac:'NAC',desc:"ASHOK LEYLAND VK2011.4T6R — 5.57m WB · 'H' Series iGen6 6-cyl BS VI (197 HP) · 6-speed OD gearbox · Rubber-ended suspension · Tilt & Telescopic steering · EB, ESC · 7 × 295/80 R22.5 TL"},
  'CCV20114D00110':{fam:'CCV',model:'Viking',oll:11.4,fuel:'D',ac:'NAC',desc:"ASHOK LEYLAND VK2011.4T6R — 5.57m WB · 'H' Series iGen6 6-cyl BS VI (197 HP) · 6-speed OD gearbox · Front rubber-ended & rear air suspension · Tilt & Telescopic steering · EB, ESC · 7 × 295/80 R22.5 TL"},
  'CCV20114D00115':{fam:'CCV',model:'Viking',oll:11.4,fuel:'D',ac:'NAC',desc:"ASHOK LEYLAND VK2011.4T6R — 5639mm WB · 'H' Series iGen6 6-cyl BS VI (197 HP) · 6-speed OD gearbox · Rubber-ended suspension · Tilt & Telescopic steering · EB, ESC · 7 × 10R20-16PR Radial"},
  'CCV20114D00114':{fam:'CCV',model:'Viking',oll:11.4,fuel:'D',ac:'NAC',desc:"ASHOK LEYLAND VK2011.4T6R — 5.29m WB · 'H' Series iGen6 6-cyl BS VI (197 HP) · 6-speed OD gearbox · Rubber-ended suspension · Tilt & Telescopic steering · EB, ESC · 7 × 295/80 R22.5 TL"},
  'CCV20114D00113':{fam:'CCV',model:'Viking',oll:11.4,fuel:'D',ac:'NAC',desc:"ASHOK LEYLAND VK2011.4T6R — 5.29m WB · 'H' Series iGen6 6-cyl BS VI (197 HP) · 6-speed OD gearbox · Front rubber-ended & rear air suspension · Tilt & Telescopic steering · EB, ESC · 7 × 295/80 R22.5 TL"},
  'CCV20109D00028':{fam:'CCV',model:'Viking',oll:10.9,fuel:'D',ac:'DDAC',desc:"ASHOK LEYLAND VK2010.9T6R — 5334mm WB · 'H' Series iGen6 6-cyl BS VI (197 HP) · 6-speed OD gearbox · Front rubber-ended & rear air suspension · DDAC bracket · Tilt & Telescopic steering · EB, ESC · 7 × 295/80 R22.5 TL (M)"},
  'CCV20109D00031':{fam:'CCV',model:'Viking',oll:10.9,fuel:'D',ac:'DDAC',desc:"ASHOK LEYLAND VK2010.9T6R — 5334mm WB · 'H' Series iGen6 6-cyl BS VI (197 HP) · 6-speed OD gearbox · Front rubber-ended & rear air suspension · DDAC bracket with Retarder · Tilt & Telescopic steering · EB, ESC · 7 × 295/80 R22.5 TL (M)"},
  'CCV20114D00112':{fam:'CCV',model:'Viking',oll:11.4,fuel:'D',ac:'DDAC',desc:"ASHOK LEYLAND VK2011.4T6R — 5639mm WB · 'H' Series iGen6 6-cyl BS VI (197 HP) · 6-speed OD gearbox · Rubber-ended suspension · DDAC bracket · Tilt & Telescopic steering · EB, ESC · 7 × 295/80 R22.5 TL"},
  'CCV20114D00106':{fam:'CCV',model:'Viking',oll:11.4,fuel:'D',ac:'DDAC',desc:"ASHOK LEYLAND VK2011.4T6R — 5639mm WB · 'H' Series iGen6 6-cyl BS VI (197 HP) · 6-speed OD gearbox · Front rubber-ended & rear air suspension · DDAC bracket · Tilt & Telescopic steering · EB, ESC · 7 × 295/80 R22.5 TL"},
  'CCV13114G00016':{fam:'CCV',model:'Viking CNG',oll:11.4,fuel:'G',ac:'NAC',desc:"ASHOK LEYLAND VK1311.4C6R — 5639mm WB · 'H' Series NA 6-cyl BS VI (127 HP) CNG engine · 6-speed gearbox · Rubber-ended suspension · 720L CNG tank · Tilt & Telescopic steering · EB, ESC · 7 × 10R20-16PR Radial"},
  'CCV13114G00017':{fam:'CCV',model:'Viking CNG',oll:11.4,fuel:'G',ac:'NAC',desc:"ASHOK LEYLAND VK1311.4C6R — 5639mm WB · 'H' Series NA 6-cyl BS VI (127 HP) CNG engine · 6-speed gearbox · Rubber-ended suspension · 840L CNG tank · Tilt & Telescopic steering · EB, ESC · 7 × 295/80 R22.5 TL"},
  'CCV22114G00010':{fam:'CCV',model:'Viking CNG TC',oll:11.4,fuel:'G',ac:'DDAC',desc:"ASHOK LEYLAND VK2211.4C6R — 5639mm WB · 'H' Series 6-cyl BS VI CNG TC engine (216 HP) · 6-speed gearbox · Rubber-ended suspension · 720L CNG tank (WB door provision) · DDAC bracket · Tilt & Telescopic steering · EB, ESC · 7 × 295/80 R22.5 TL"},
  'CCT20120D00072':{fam:'CCT',model:'12M',oll:12.0,fuel:'D',ac:'DDAC',desc:"ASHOK LEYLAND TF2012.0T6R — 6000mm WB · 'H' Series iGen6 6-cyl BS VI (197 HP) · 6-speed OD gearbox (no retarder) · Rubber-ended suspension · DDAC bracket · Unitised bearing · Tilt & Telescopic steering · EB, ESC · 7 × 295/80 R22.5 TL (M)"},
  'CCT20120D00069':{fam:'CCT',model:'12M',oll:12.0,fuel:'D',ac:'DDAC',desc:"ASHOK LEYLAND TF2012.0T6R — 6000mm WB · 'H' Series iGen6 6-cyl BS VI (197 HP) · 6-speed OD gearbox (no retarder) · Front rubber-ended & rear air suspension · DDAC bracket · Tilt & Telescopic steering · EB, ESC · 7 × 295/80 R22.5 TL"},
  'CCT20120D00071':{fam:'CCT',model:'12M',oll:12.0,fuel:'D',ac:'DDAC',desc:"ASHOK LEYLAND TF2012.0T6R — 6000mm WB · 'H' Series iGen6 6-cyl BS VI (197 HP) · 6-speed OD gearbox (no retarder) · Front rubber-ended & rear air suspension · DDAC bracket · Front disc brake · Unitised bearing · 7 × 295/80 R22.5 TL (M)"},
  'CCT20120D00073':{fam:'CCT',model:'12M',oll:12.0,fuel:'D',ac:'DDAC',desc:"ASHOK LEYLAND TF2012.0T6R — 6000mm WB · 'H' Series iGen6 6-cyl BS VI (197 HP) · 6-speed OD gearbox (no retarder) · Full air suspension · DDAC bracket · Tilt & Telescopic steering · EB, ESC · 7 × 295/80 R22.5 TL"},
  'CCT20120D00078':{fam:'CCT',model:'12M',oll:12.0,fuel:'D',ac:'NAC',desc:"ASHOK LEYLAND TF2012.0T6R — 6000mm WB · 'H' Series iGen6 6-cyl BS VI (197 HP) · 6-speed OD gearbox (no retarder) · Full air suspension · Non-AC · Tilt & Telescopic steering · EB, ESC · 7 × 295/80 R22.5 TL"},
  'CCT20120D00075':{fam:'CCT',model:'12M',oll:12.0,fuel:'D',ac:'DDAC',desc:"ASHOK LEYLAND TF2012.0T6R — 6000mm WB · 'H' Series iGen6 6-cyl BS VI (197 HP) · 6-speed OD gearbox (no retarder) · Full air suspension · DDAC bracket · Front disc brake · Unitised bearing · EB, ESC · 7 × 295/80 R22.5 TL (M)"},
  'CCT20120D00074':{fam:'CCT',model:'12M',oll:12.0,fuel:'D',ac:'DDAC',desc:"ASHOK LEYLAND TF2012.0T6R — 6000mm WB · 'H' Series iGen6 6-cyl BS VI (197 HP) · 6-speed OD gearbox with Retarder · Front rubber-ended & rear air suspension · DDAC bracket · 375L Polymer tank · EB, ESC · 7 × 295/80 R22.5 TL"},
  'CCT20120D00070':{fam:'CCT',model:'12M',oll:12.0,fuel:'D',ac:'DDAC',desc:"ASHOK LEYLAND TF2012.0T6R — 6000mm WB · 'H' Series iGen6 6-cyl BS VI (197 HP) · 6-speed OD gearbox with Retarder · Front rubber-ended & rear air suspension · DDAC bracket · Front disc brake · Unitised bearing · EB, ESC · 7 × 295/80 R22.5 TL (M)"},
  'CCT20120D00076':{fam:'CCT',model:'12M',oll:12.0,fuel:'D',ac:'DDAC',desc:"ASHOK LEYLAND TF2012.0T6R — 6000mm WB · 'H' Series iGen6 6-cyl BS VI (197 HP) · 6-speed OD gearbox with Retarder · Full air suspension · DDAC bracket · Front disc brake · Unitised bearing · EB, ESC · 7 × 295/80 R22.5 TL (M)"},
  'CCT20120D00077':{fam:'CCT',model:'12M',oll:12.0,fuel:'D',ac:'DDAC',desc:"ASHOK LEYLAND TF2012.0T6R — 6000mm WB · 'H' Series iGen6 6-cyl BS VI (197 HP) · 6-speed OD gearbox with Retarder · Front rubber-ended & rear air suspension · DDAC bracket · EB, ESC · 7 × 295/80 R22.5 TL"},
  'CCT25120D00023':{fam:'CCT',model:'12M 250HP',oll:12.0,fuel:'D',ac:'DDAC',desc:"ASHOK LEYLAND TF2512.0F6R — 6000mm WB · 'A' Series iGen6 4-cyl BS VI (248 HP) · 6-speed OD gearbox with Retarder · Full air suspension · DDAC bracket · Front disc brake · Unitised bearing · EB, ESC · 7 × 295/80 R22.5 TL (M)"},
  'CCN25135D00023':{fam:'CCN',model:'Garud 13.5M',oll:13.5,fuel:'D',ac:'DDAC',desc:"ASHOK LEYLAND TF2513.5F6R — 7000mm WB · 'H64V' Series iGen6 6-cyl BS VI (247 HP) · 6MT86 gearbox (no retarder) · Front rubber-ended & rear air suspension · DDAC bracket · Front disc brake · Unitised bearing · ESC · 7 × 295/80 R22.5 TL (M)"},
  'CCN25135D00027':{fam:'CCN',model:'Garud 13.5M',oll:13.5,fuel:'D',ac:'DDAC',desc:"ASHOK LEYLAND TF2513.5F6R — 7000mm WB · 'H64V' Series iGen6 6-cyl BS VI (247 HP) · 6MT86 gearbox · Full air suspension · DDAC bracket · Retarder · ESC · 7 × 295/80 R22.5 TL (M)"},
  'CCN25135D00025':{fam:'CCN',model:'Garud 13.5M',oll:13.5,fuel:'D',ac:'DDAC',desc:"ASHOK LEYLAND TF2513.5F6R — 7000mm WB · 'H64V' Series iGen6 6-cyl BS VI (247 HP) · 6MT86 gearbox with Retarder · Front rubber-ended & rear air suspension · DDAC bracket · Front disc brake · Unitised bearing · ESC · 7 × 295/80 R22.5 TL (M)"},
  'CCN25135D00037':{fam:'CCN',model:'Garud 13.5M',oll:13.5,fuel:'D',ac:'DDAC',desc:"ASHOK LEYLAND TF2513.5F6R — 7000mm WB · 'H64V' Series iGen6 6-cyl BS VI (247 HP) · 6MT86 gearbox (no retarder) · Full air suspension · DDAC bracket · Front disc brake · Unitised bearing · ESC · 7 × 295/80 R22.5 TL (M)"},
  'CCN25135D00026':{fam:'CCN',model:'Garud 13.5M',oll:13.5,fuel:'D',ac:'DDAC',desc:"ASHOK LEYLAND TF2513.5F6R — 7000mm WB · 'H64V' Series iGen6 6-cyl BS VI (247 HP) · 6MT86 gearbox with Retarder · Full air suspension · DDAC bracket · Front disc brake · Unitised bearing · ESC · 7 × 295/80 R22.5 TL (M)"},
  'CCS15081D00005':{fam:'CCS',model:'Sunshine',oll:8.1,fuel:'D',ac:'NAC',desc:"ASHOK LEYLAND SS1508.1T6R — 4560mm WB · 150HP BS VI engine · ESC · 7 × 7.50×16"},
  'CCS15094D00005':{fam:'CCS',model:'Sunshine',oll:9.4,fuel:'D',ac:'NAC',desc:"ASHOK LEYLAND SS1509.4T6R — 5200mm WB · 150HP BS VI engine · ESC · 7 × 7.50×16"},
  'CCL15087D00029':{fam:'CCL',model:'Lynx Smart',oll:8.7,fuel:'D',ac:'NAC',desc:"ASHOK LEYLAND LS1508.7T6RL — 4200mm WB Chassis · ESC · 7 × 7.50×16"},
  'CCL15099D00016':{fam:'CCL',model:'Lynx Smart',oll:9.9,fuel:'D',ac:'NAC',desc:"ASHOK LEYLAND LS1509.9T6RL — 4900mm WB Chassis · ESC · 7 × 7.50×16"},
  'CCL15103D00028':{fam:'CCL',model:'Lynx Smart',oll:10.3,fuel:'D',ac:'NAC',desc:"ASHOK LEYLAND LS1510.3T6RL — 5200mm WB Chassis · ESC · 7 × 8.25×16"},
  'CCL15103D00031':{fam:'CCL',model:'Lynx Smart',oll:10.3,fuel:'D',ac:'NAC',desc:"ASHOK LEYLAND LS1510.3T6RL — 5200mm WB · LYNX MAX NAC Chassis · ESC · 7 × 235/75 R17.5"},
  'CCL15103D00020':{fam:'CCL',model:'Lynx Smart',oll:10.3,fuel:'D',ac:'NAC',desc:"ASHOK LEYLAND LS1510.3T6R — 5200mm WB Chassis · ESC · 7 × 235/75 R17.5"},
  'CCL15103D00047':{fam:'CCL',model:'Lynx Smart',oll:10.3,fuel:'D',ac:'NAC',desc:"ASHOK LEYLAND LS1510.3T6R — 5200mm WB Chassis (Mofussil) · ESC · 7 × 235/75 R17.5"},
  'CCL15103D00046':{fam:'CCL',model:'Lynx Smart',oll:10.3,fuel:'D',ac:'NAC',desc:"ASHOK LEYLAND LS1510.3T6R — 5200mm WB Chassis (Mofussil) · ESC · 7 × 8.25×16"},
  'CCL15099D00028':{fam:'CCL',model:'Lynx Smart',oll:9.9,fuel:'D',ac:'NAC',desc:"ASHOK LEYLAND LS1509.9T6R — 4900mm WB Chassis · ESC · 7 × 235/75 R17.5"},
  'CCL15099D00017':{fam:'CCL',model:'Lynx Smart',oll:9.9,fuel:'D',ac:'NAC',desc:"ASHOK LEYLAND LS1509.9T6RL — 4900mm WB Chassis · ESC · 7 × 235/75 R17.5"},
  'CCL15099D00035':{fam:'CCL',model:'Lynx Smart',oll:9.9,fuel:'D',ac:'NAC',desc:"ASHOK LEYLAND LS1509.9T6RL — 4900mm WB Chassis · ESC · 7 × 8.25×16"},
  'CCL15087D00018':{fam:'CCL',model:'Lynx Smart',oll:8.7,fuel:'D',ac:'NAC',desc:"ASHOK LEYLAND LS1508.7T6R — 4200mm WB Chassis · ESC · 7 × 235/75 R17.5"},
  'CCL15087D00038':{fam:'CCL',model:'Lynx Smart',oll:8.7,fuel:'D',ac:'NAC',desc:"ASHOK LEYLAND LS1508.7T6R — 4200mm WB Chassis · ESC · 7 × 7.50×16"},
  'CCL15079D00016':{fam:'CCL',model:'Lynx Smart',oll:7.9,fuel:'D',ac:'NAC',desc:"ASHOK LEYLAND LS1507.9T6R — 3900mm WB · LYNX MAX NAC Chassis · ESC · 7 × 235/75 R17.5"},
  'CCL15079D00009':{fam:'CCL',model:'Lynx Smart',oll:7.9,fuel:'D',ac:'NAC',desc:"ASHOK LEYLAND LS1507.9T6R — 3900mm WB Chassis · ESC · 7 × 235/75 R17.5"},
  'CCL15079D00017':{fam:'CCL',model:'Lynx Smart',oll:7.9,fuel:'D',ac:'NAC',desc:"ASHOK LEYLAND LS1507.9T6R — 3900mm WB Chassis · ESC · 7 × 7.50×16"},
  'CCL15103D00036':{fam:'CCL',model:'Lynx Smart',oll:10.3,fuel:'D',ac:'TM43',desc:"ASHOK LEYLAND LS1510.3T6RL — 5200mm WB · LYNX MAX AC Chassis · TM-43 A/C Compressor (engine-mounted) · ESC · 7 × 235/75 R17.5"},
  'CCL15103D00024':{fam:'CCL',model:'Lynx Smart',oll:10.3,fuel:'D',ac:'TM43',desc:"ASHOK LEYLAND LS1510.3T6R — 5200mm WB Chassis · TM-43 A/C Compressor (engine-mounted) · ESC · 7 × 235/75 R17.5"},
  'CCL15099D00026':{fam:'CCL',model:'Lynx Smart',oll:9.9,fuel:'D',ac:'TM43',desc:"ASHOK LEYLAND LS1509.9T6R — 4900mm WB Chassis · TM-43 A/C Compressor (engine-mounted) · ESC · 7 × 235/75 R17.5"},
  'CCL15087D00017':{fam:'CCL',model:'Lynx Smart',oll:8.7,fuel:'D',ac:'TM43',desc:"ASHOK LEYLAND LS1508.7T6R — 4200mm WB Chassis · TM-43 A/C Compressor (engine-mounted) · ESC · 7 × 235/75 R17.5"},
  'CCL15079D00015':{fam:'CCL',model:'Lynx Smart',oll:7.9,fuel:'D',ac:'TM43',desc:"ASHOK LEYLAND LS1507.9T6R — 3900mm WB Chassis · TM-43 A/C Compressor (engine-mounted) · ESC · 7 × 235/75 R17.5"},
  'CCL15103D00025':{fam:'CCL',model:'Lynx Smart',oll:10.3,fuel:'D',ac:'TM43',desc:"ASHOK LEYLAND LS1510.3T6R — 5200mm WB Chassis · TM-43 A/C Compressor (engine-mounted) · AMT · Air suspension · ESC · 7 × 235/75 R17.5"},
  'CCL15103D00048':{fam:'CCL',model:'Lynx Smart',oll:10.3,fuel:'D',ac:'TM43',desc:"ASHOK LEYLAND LS1510.3T6R — 5200mm WB Chassis · TM-43 A/C Compressor (engine-mounted) · Rear air suspension · ESC · 7 × 235/75 R17.5"},
  'CCL15099D00034':{fam:'CCL',model:'Lynx Smart',oll:9.9,fuel:'D',ac:'TM43',desc:"ASHOK LEYLAND LS1509.9T6R — 4900mm WB Chassis · TM-43 A/C Compressor (engine-mounted) · Rear air suspension · ESC · 7 × 235/75 R17.5"},
  'CCL15087D00037':{fam:'CCL',model:'Lynx Smart',oll:8.7,fuel:'D',ac:'TM43',desc:"ASHOK LEYLAND LS1508.7T6R — 4200mm WB Chassis · TM-43 A/C Compressor (engine-mounted) · Rear air suspension · ESC · 7 × 235/75 R17.5"},
  'CCL10099G00004':{fam:'CCL',model:'Lynx Smart CNG',oll:9.9,fuel:'G',ac:'NAC',desc:"ASHOK LEYLAND LS1009.9C6RV — 4900mm WB Chassis · 480WLC CNG tank · School · ESC · 7 × 8.25×16"},
  'CCL10099G00003':{fam:'CCL',model:'Lynx Smart CNG',oll:9.9,fuel:'G',ac:'NAC',desc:"ASHOK LEYLAND LS1009.9C6RV — 4900mm WB Chassis · 480WLC CNG tank · Staff · ESC · 7 × 235/75 R17.5"},
  'CCL15099G00031':{fam:'CCL',model:'Lynx Smart CNG',oll:9.9,fuel:'G',ac:'NAC',desc:"ASHOK LEYLAND LS1509.9C6RV — 4900mm WB Chassis · 480WLC CNG tank · ESC · 7 × 8.25×16"},
  'CCL15103G00027':{fam:'CCL',model:'Lynx Smart CNG',oll:10.3,fuel:'G',ac:'NAC',desc:"ASHOK LEYLAND LS1510.3C6RVL — 5200mm WB Chassis · 480WLC CNG tank · ESC · 7 × 235/75 R17.5"},
  'CCL15103G00033':{fam:'CCL',model:'Lynx Smart CNG',oll:10.3,fuel:'G',ac:'NAC',desc:"ASHOK LEYLAND LS1510.3C6RVL — 5200mm WB · LYNXMAX Chassis · 480WLC CNG tank · ESC · 7 × 235/75 R17.5"},
  'CCL15103G00028':{fam:'CCL',model:'Lynx Smart CNG',oll:10.3,fuel:'G',ac:'TM43',desc:"ASHOK LEYLAND LS1510.3C6RVL — 5200mm WB Chassis · 480WLC CNG tank · TM-43 A/C Compressor (engine-mounted) · 6-speed · ESC · 7 × 235/75 R17.5"},
  'CCL15103G00036':{fam:'CCL',model:'Lynx Smart CNG',oll:10.3,fuel:'G',ac:'TM43',desc:"ASHOK LEYLAND LS1510.3C6RVL — 5200mm WB · LYNXMAX Chassis · 480WLC CNG tank · TM-43 A/C Compressor (engine-mounted) · ESC · 7 × 235/75 R17.5"},
  'CCG15099D00011':{fam:'CCG',model:'Lynx Strong',oll:9.9,fuel:'D',ac:'NAC',desc:"ASHOK LEYLAND LT1509.9T6R — 4900mm WB Chassis · ESC · 7 × 9R20"},
  'CCG15106D00011':{fam:'CCG',model:'Lynx Strong',oll:10.6,fuel:'D',ac:'NAC',desc:"ASHOK LEYLAND LT1510.6T6R — 5334mm WB Chassis · 12V · ESC · 7 × 10R20"},
  'CCG15106D00012':{fam:'CCG',model:'Lynx Strong',oll:10.6,fuel:'D',ac:'NAC',desc:"ASHOK LEYLAND LT1510.6T6R — 5334mm WB Chassis · 24V · ESC · 7 × 10R20"},
  'CCG15106D00013':{fam:'CCG',model:'Lynx Strong',oll:10.6,fuel:'D',ac:'NAC',desc:"ASHOK LEYLAND LT1510.6T6R — 5334mm WB Chassis · 24V · Air suspension · ESC · 7 × 10R20"},
  'CCG15111D00013':{fam:'CCG',model:'Lynx Strong',oll:11.1,fuel:'D',ac:'NAC',desc:"ASHOK LEYLAND LT1511.1T6R — 5639mm WB Chassis · 12V · ESC · 7 × 10R20"},
  'CCG15111D00014':{fam:'CCG',model:'Lynx Strong',oll:11.1,fuel:'D',ac:'NAC',desc:"ASHOK LEYLAND LT1511.1T6R — 5639mm WB Chassis · 24V · ESC · 7 × 10R20"},
  'CCG15111D00015':{fam:'CCG',model:'Lynx Strong',oll:11.1,fuel:'D',ac:'NAC',desc:"ASHOK LEYLAND LT1511.1T6R — 5639mm WB Chassis · 24V · Air suspension · ESC · 7 × 10R20"},
  'CCG15099D00009':{fam:'CCG',model:'Lynx Strong',oll:9.9,fuel:'D',ac:'TM43',desc:"ASHOK LEYLAND LT1509.9T6R — 4900mm WB Chassis · TM-43 A/C Compressor (engine-mounted) · ESC · 7 × 9R20"},
  'CCG15106G00004':{fam:'CCG',model:'Lynx Strong CNG',oll:10.6,fuel:'G',ac:'NAC',desc:"ASHOK LEYLAND LT1510.6C6R — 5334mm WB Chassis · 600WLC CNG tank · ESC · 7 × 9.00R20"},
  'CCG15111G00005':{fam:'CCG',model:'Lynx Strong CNG',oll:11.1,fuel:'G',ac:'NAC',desc:"ASHOK LEYLAND LT1511.6C6R — 5639mm WB Chassis · 660WLC CNG tank · ESC · 7 × 10.00R20"},
  'CCG15106G00008':{fam:'CCG',model:'Lynx Strong CNG',oll:10.6,fuel:'G',ac:'NAC',desc:"ASHOK LEYLAND LT1510.6C6R — 5334mm WB Chassis · 600WLC CNG tank · Air suspension · ESC · 7 × 9.00R20"},
  'CCG15111G00006':{fam:'CCG',model:'Lynx Strong CNG',oll:11.1,fuel:'G',ac:'NAC',desc:"ASHOK LEYLAND LT1511.6C6R — 5639mm WB Chassis · 660WLC CNG tank · Air suspension · ESC · 7 × 10.00R20"},
  // New entries for Apr 2026:
  'CCF25150D00005':{fam:'CCF',model:'Garud 15M',oll:15.0,fuel:'D',ac:'DDAC',desc:"ASHOK LEYLAND FM2515.0F6R — 7650mm WB · 'A' Series iGen6 4-cyl BS VI (248 HP) · 6MT DD gearbox with Retarder · Front rubber-ended & rear air suspension · DDAC bracket · Front disc brake · Unitised bearing · ESC · 7 × 295/80 R22.5 TL"},
  'CCF25150D00006':{fam:'CCF',model:'Garud 15M',oll:15.0,fuel:'D',ac:'DDAC',desc:"ASHOK LEYLAND FM2515.0F6R — 7650mm WB · 'A' Series iGen6 4-cyl BS VI (248 HP) · 6MT DD gearbox with Retarder · Front & rear full air suspension · DDAC bracket · Front disc brake · Unitised bearing · ESC · 7 × 295/80 R22.5 TL"},
  'CCL15099G00028':{fam:'CCL',model:'Lynx Smart CNG',oll:9.9,fuel:'G',ac:'TM43',desc:"ASHOK LEYLAND LS1509.9C6RVL — 4900mm WB Chassis · 480WLC CNG tank · TM-43 A/C Compressor (engine-mounted) · ESC · 7 × 235/75 R17.5"},
}

// Filter Apr 2026 bus rows: only cowl chassis (CC* or CCF* prefix; exclude CBL, CBG, CES)
const busRows = allRows.filter(r =>
  (r.segment === 'Bus – ICV' || r.segment === 'Bus – MCV') &&
  r.cbn.match(/^CC/)
)

const jsLines = [
  `// ── Chassis Database (${busRows.length} AL Bus Cowl Chassis — Apr 2026) ──────────────────────`,
  'const DB = [',
]
busRows.forEach(r => {
  const c = CURATED[r.cbn]
  if (!c) {
    process.stderr.write(`⚠ No curated entry for ${r.cbn} — skipping\n`)
    return
  }
  const entry = `  {cbn:"${r.cbn}",fam:"${c.fam}",model:"${c.model}",desc:"${c.desc}",oll:${c.oll},fuel:"${c.fuel}",ac:"${c.ac}",mrp:${r.mrp}},`
  jsLines.push(entry)
})
jsLines.push(']')

fs.writeFileSync(path.join(OUT, 'bus_db_apr2026.js'), jsLines.join('\n') + '\n')
process.stderr.write(`✓ Bus DB → _out/bus_db_apr2026.js (${busRows.length} rows)\n`)

// ── C) EMI Calculator array ───────────────────────────────────────────────────
// Format: {s, m, p} — segment display name, model name, min MRP in sub_category
// EMI calc shows segment groups: Buses, Haulage, ICV Trucks, Tippers

const segMap = {
  'Bus – ICV':      'Buses',
  'Bus – MCV':      'Buses',
  'ICV Truck':      'ICV Trucks',
  'MBP Truck':      'Haulage',
  'Tipper':         'Tippers',
  'RMC / Boom Pump':'Tippers',
}

// Group by (display_segment, sub_cat) → min MRP
const emiMap = {}
allRows.forEach(r => {
  const s = segMap[r.segment]
  if (!s) return
  // Use sub_cat as model name
  const key = `${s}__${r.sub_cat}`
  if (!emiMap[key] || r.mrp < emiMap[key].p) {
    emiMap[key] = { s, m: r.sub_cat, p: r.mrp }
  }
})

// Sort by segment order then model name
const SEG_ORDER = ['Buses', 'ICV Trucks', 'Haulage', 'Tippers']
const emiRows = Object.values(emiMap).sort((a, b) => {
  const si = SEG_ORDER.indexOf(a.s) - SEG_ORDER.indexOf(b.s)
  return si !== 0 ? si : a.m.localeCompare(b.m)
})

const emiJs = [
  '// AL Vehicle price list — Apr 2026 (entry-level MRP per sub-category)',
  '// Format: {s: segment, m: model/sub-category, p: min MRP incl. 18% GST}',
  'var alVehicles = [',
  ...emiRows.map(r => `  {s:"${r.s}",m:"${r.m}",p:${r.p}},`),
  ']',
]
fs.writeFileSync(path.join(OUT, 'emi_vehicles_apr2026.js'), emiJs.join('\n') + '\n')
process.stderr.write(`✓ EMI array → _out/emi_vehicles_apr2026.js (${emiRows.length} models)\n`)

// ── D) Featured model avg prices for ashok-leyland.html ───────────────────────
// 1. Ecomet 1615 → ICV Truck, sub_cat contains "Ecomet" (Boss 16T variant)
//    Actually: avg of "Boss 16T" or "Ecomet" sub_cat
// 2. 3520 8x2 LA → MBP Truck, sub_cat "3520" or similar
// 3. 2825 6x4 Tipper → Tipper, sub_cat "2825" or similar
// 4. Viking 12M AC → Bus – MCV, 12M Coach, DDAC, diesel
// 5. Boss 1415 → ICV Truck, sub_cat contains "Boss 14T"
// 6. Tractor 5525 → MBP Truck, sub_cat "5525" or similar

function avgByFilter(filterFn) {
  const matches = allRows.filter(filterFn)
  if (!matches.length) return null
  const avg = matches.reduce((s, r) => s + r.mrp, 0) / matches.length
  return avg
}
function lakhs(v, dp = 1) {
  return (v / 100000).toFixed(dp)
}

const featured = {
  'Ecomet 1615 (ICV 16T)': avgByFilter(r => r.segment === 'ICV Truck' && /ecomet|boss.*16t/i.test(r.sub_cat)),
  '3520 8x2 LA (MBP 35T)': avgByFilter(r => r.segment === 'Long Haul Trucks' && /3520/i.test(r.sub_cat || r.desc)),
  '2825 6x4 Tipper':        avgByFilter(r => r.segment === 'Tipper'    && /2825/i.test(r.sub_cat || r.desc)),
  'Viking 12M AC (Bus MCV)':avgByFilter(r => r.segment === 'Bus – MCV' && /12m/i.test(r.sub_cat) && /ddac/i.test(r.desc)),
  'Boss 1415 (ICV 14T)':    avgByFilter(r => r.segment === 'ICV Truck' && /boss.*14t/i.test(r.sub_cat)),
  'Tractor 5525 (MBP)':     avgByFilter(r => r.segment === 'Long Haul Trucks' && /5525/i.test(r.sub_cat || r.desc)),
}

// Fall back to broader segment average if specific match not found
if (!featured['Ecomet 1615 (ICV 16T)']) {
  featured['Ecomet 1615 (ICV 16T)'] = avgByFilter(r => r.segment === 'ICV Truck' && /16t|1615/i.test(r.sub_cat || r.desc))
}
if (!featured['3520 8x2 LA (MBP 35T)']) {
  featured['3520 8x2 LA (MBP 35T)'] = avgByFilter(r => r.segment === 'Long Haul Trucks' && /3520/i.test(r.desc))
}
if (!featured['Tractor 5525 (MBP)']) {
  featured['Tractor 5525 (MBP)'] = avgByFilter(r => r.segment === 'Long Haul Trucks' && /5525|tractor/i.test(r.desc))
}

const alTxt = [
  'Featured model avg prices — Apr 2026 (for ashok-leyland.html)',
  'Format: Avg. ₹XX.XL',
  '',
  ...Object.entries(featured).map(([name, avg]) =>
    avg ? `${name}: Avg. ₹${lakhs(avg)}L` : `${name}: NOT FOUND — check sub_cat manually`
  ),
  '',
  'Sub-categories available in new price list:',
  ...Object.entries(
    allRows.reduce((acc, r) => { (acc[r.segment] = acc[r.segment] || new Set()).add(r.sub_cat); return acc }, {})
  ).map(([seg, subs]) => `  ${seg}: ${[...subs].sort().join(', ')}`)
]
fs.writeFileSync(path.join(OUT, 'al_page_prices_apr2026.txt'), alTxt.join('\n') + '\n')
process.stderr.write(`✓ AL page prices → _out/al_page_prices_apr2026.txt\n`)
process.stderr.write(`\nDone. All outputs in scripts/_out/\n`)
