// Run: node scripts/generate_seed.js > seed_vehicles.sql
const XLSX = require('xlsx')

const wb = XLSX.readFile('D:/PTB/Website/parastrucks/pricelist/AL_Price_Database_Sep2025.xlsx')
const ws = wb.Sheets['Price Database']
const rows = XLSX.utils.sheet_to_json(ws, { header: 1, defval: '' }).slice(1)

// ── Segment mapping ────────────────────────────────────────────────────────
function mapSegment(cat, excelSubcat) {
  if (cat === 'ICV Trucks') return 'ICV Trucks'
  if (cat === 'Tipper') return 'Tippers'
  if (cat === 'Bus / Passenger') return 'Buses'
  if (cat === 'Long Haul / MBP Trucks') {
    // Tractor heads → own segment
    if (excelSubcat.toLowerCase().includes('tractor')) return 'Tractors'
    return 'Long Haul'
  }
  return cat
}

// ── GVW extraction ─────────────────────────────────────────────────────────
function extractGVW(desc) {
  const m = desc.match(/([\d.]+)\s*T\s*GVW/i)
  return m ? parseFloat(m[1]) : null
}

// ── Long haul GVW from model number ──────────────────────────────────────
// CBN encodes GVW×10 in the first 3 digits after the 2-char category prefix
// e.g. CDB192018 → 192 → 19.2T | CHU282022 → 282 → 28.2T | CHU352024 → 352 → 35.2T
function longHaulGVW(cbn, subcat) {
  if (subcat.toLowerCase().includes('tractor')) return null
  const m = cbn.match(/^C[A-Z]{2}(\d{3})/)
  if (!m) return null
  const gvwX10 = parseInt(m[1])   // 192 → 19.2T, 282 → 28.2T, 352 → 35.2T etc.
  if (gvwX10 <= 250) return 19
  if (gvwX10 <= 370) return 28
  return 42
}

// ── sub_category logic ────────────────────────────────────────────────────
function getSubCategory(segment, gvw, cbn, excelSubcat) {
  if (segment === 'ICV Trucks') {
    if (gvw === null) return 'ICV'
    if (gvw < 10)  return 'Up to 10T'
    if (gvw < 12)  return '10T–12T'
    if (gvw < 16)  return '12T–16T'
    return '16T+'
  }

  if (segment === 'Long Haul') {
    const g = longHaulGVW(cbn, excelSubcat)
    if (g === null) return 'Long Haul'
    if (g <= 22) return 'Up to 25T'
    if (g <= 36) return '25T–40T'
    return '40T+'
  }

  if (segment === 'Tractors') {
    // e.g. Tractor 4020 → 40T GCW, 4620 → 46T, 5525 → 55T
    if (excelSubcat.includes('4020')) return 'Up to 42T'
    if (excelSubcat.includes('4620')) return 'Up to 49T'
    return '55T+'
  }

  if (segment === 'Tippers') {
    const s = excelSubcat.toLowerCase()
    if (s.includes('rmc')) return 'RMC Mixer'
    if (s.includes('10x4') || s.includes('10×4')) return '10×4 (48T)'
    if (s.includes('8x4')  || s.includes('8×4'))  return '8×4 (35T)'
    if (s.includes('6x4')  || s.includes('6×4'))  return '6×4 (28–32T)'
    return '4×2 (19T)'
  }

  if (segment === 'Buses') {
    const s = excelSubcat.toLowerCase()
    if (s.includes('sunshine') || s.includes('cheetah')) return 'Mini / MCV Bus'
    if (s.includes('lynx smart') || s.includes('lynx strong')) return 'Standard Bus'
    if (s.includes('viking'))   return 'City Bus'
    if (s.includes('garud'))    return 'Coach'
    if (s.includes('12m'))      return 'Coach'
    if (s.includes('oyster'))   return 'Staff / School Bus'
    return 'Bus'
  }

  return excelSubcat
}

// ── Generate SQL ───────────────────────────────────────────────────────────
const esc = s => s ? s.replace(/'/g, "''") : ''

const lines = [
  '-- Vehicle catalog seed — AL Sep 2025 price circular',
  '-- Generated by scripts/generate_seed.js',
  '',
  "INSERT INTO public.vehicle_catalog",
  "  (cbn, description, segment, sub_category, tyres, base_price, dealer_markup, mrp_incl_gst, gst_rate, price_circular, effective_date)",
  'VALUES',
]

const values = []

for (const row of rows) {
  const [, cat, excelSubcat, cbn, desc, tyres, base, markup, mrp] = row
  if (!cbn || !desc) continue

  const segment = mapSegment(cat, excelSubcat)
  const gvw = extractGVW(desc)
  const subCat = getSubCategory(segment, gvw, cbn, excelSubcat)

  values.push(
    `  ('${esc(cbn)}', '${esc(desc)}', '${esc(segment)}', '${esc(subCat)}', ` +
    `'${esc(tyres)}', ${base}, ${markup}, ${mrp}, 18, 'Sep2025', '2025-09-22')`
  )
}

lines.push(values.join(',\n') + ';')

process.stdout.write(lines.join('\n') + '\n')
process.stderr.write(`Generated ${values.length} vehicle rows.\n`)
