// Generate vehicle catalog seed from AL_Vehicle_Price_List_Sep2025.xlsx
// Run: node scripts/generate_seed.cjs > seed_vehicles.sql
const XLSX = require('xlsx')

const SOURCE = 'D:/PTB/Website/parastrucks/pricelist/AL_Vehicle_Price_List_Sep2025.xlsx'
const SHEET  = 'Vehicle Price List'

const wb   = XLSX.readFile(SOURCE)
const ws   = wb.Sheets[SHEET]
const rows = XLSX.utils.sheet_to_json(ws, { header: 1, defval: '' }).slice(1) // skip header row

// Columns: [0] Segment, [1] Sub-Category, [2] CBN, [3] Description, [4] Tyres, [5] MRP incl. 18% GST

const esc = s => String(s ?? '').replace(/'/g, "''").trim()

const lines = [
  '-- Vehicle catalog seed — Ashok Leyland Sep 2025 price list',
  '-- Source: AL_Vehicle_Price_List_Sep2025.xlsx',
  '-- Generated by scripts/generate_seed.cjs',
  '',
  'TRUNCATE public.vehicle_catalog RESTART IDENTITY CASCADE;',
  '',
  'INSERT INTO public.vehicle_catalog',
  '  (cbn, description, segment, sub_category, tyres, mrp_incl_gst, gst_rate, price_circular, effective_date)',
  'VALUES',
]

const values = []

for (const row of rows) {
  const [segment, subcat, cbn, desc, tyres, mrpRaw] = row

  if (!cbn || !desc) continue

  // Tyres column is a real tyre spec only when it differs from description
  const tyresVal = (tyres && tyres !== desc) ? `'${esc(tyres)}'` : 'NULL'

  // MRP is stored as a number but may have commas/symbols in some locales
  const mrp = parseInt(String(mrpRaw).replace(/[^0-9]/g, ''), 10)
  if (!mrp || mrp <= 0) continue

  values.push(
    `  ('${esc(cbn)}', '${esc(desc)}', '${esc(segment)}', '${esc(subcat)}', ` +
    `${tyresVal}, ${mrp}, 18, 'Sep2025', '2025-09-01')`
  )
}

lines.push(values.join(',\n') + ';')
lines.push('')
lines.push(`-- ${values.length} rows inserted`)

process.stdout.write(lines.join('\n') + '\n')
process.stderr.write(`Generated ${values.length} vehicle rows.\n`)
