-- TIV Forecast — atomic upload + pre-upload snapshot (UI/UX audit findings A4, C7)
--
-- Before this, an upload was EIGHT independent Edge Function calls: six table
-- upserts, a model-params insert, then an upload-history insert. A failure at
-- step 4 left production half-overwritten -- new actuals sitting under the old
-- model -- with an error message that named no step, and no history row at all
-- because history was written last. A failure of the history insert ALONE
-- reported "Upload failed" for an upload that had fully committed.
--
-- A PL/pgSQL function body runs inside a single transaction, so everything here
-- either lands together or not at all. No compensating-rollback logic to get
-- wrong.
--
-- ADDITIVE ONLY: one new table, one new function. Nothing dropped or altered.
-- Owner approved the new table on 2026-08-25.

-- ── 1. Snapshots ────────────────────────────────────────────────────────────
-- There is no undo for an upload, and the UI never said so. One row per upload
-- holding everything that entity/brand had a moment before -- about 50 months
-- across six tables, which is small enough to keep indefinitely.
CREATE TABLE IF NOT EXISTS public.tiv_forecast_snapshots (
  id          bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  entity_id   uuid NOT NULL REFERENCES public.entities(id),
  brand_id    uuid NOT NULL REFERENCES public.brands(id),
  taken_at    timestamptz NOT NULL DEFAULT now(),
  taken_by    uuid REFERENCES public.users(id),
  reason      text NOT NULL DEFAULT 'pre-upload',
  payload     jsonb NOT NULL
);

COMMENT ON TABLE public.tiv_forecast_snapshots IS
  'Pre-upload copy of every TIV table for one entity/brand, so an upload can be reverted. Written inside the same transaction as the upload by tiv_upload_all().';

CREATE INDEX IF NOT EXISTS tiv_forecast_snapshots_scope_idx
  ON public.tiv_forecast_snapshots (entity_id, brand_id, taken_at DESC);

ALTER TABLE public.tiv_forecast_snapshots ENABLE ROW LEVEL SECURITY;

-- Admin-only, and read-only even for them: snapshots are written by the
-- SECURITY DEFINER function, never by a client.
DROP POLICY IF EXISTS tiv_forecast_snapshots_select ON public.tiv_forecast_snapshots;
CREATE POLICY tiv_forecast_snapshots_select ON public.tiv_forecast_snapshots
  FOR SELECT TO authenticated
  USING ((SELECT current_user_role()) = 'admin');

-- ── 2. Atomic upload ────────────────────────────────────────────────────────
CREATE OR REPLACE FUNCTION public.tiv_upload_all(
  p_entity_id       uuid,
  p_brand_id        uuid,
  p_tiv             jsonb,
  p_ptb             jsonb,
  p_al              jsonb,
  p_judg_tiv        jsonb,
  p_judg_ptb        jsonb,
  p_raw             jsonb,
  p_params          jsonb,
  p_uploaded_by     uuid,
  p_uploader_name   text,
  p_file_name       text,
  p_months_loaded   integer,
  p_last_data_month text
) RETURNS jsonb
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $fn$
DECLARE
  v_snapshot_id bigint;
  v_conflict    text;
BEGIN
  -- Guard against the documented multi-entity/brand defect
  -- (docs/backlog/tiv-multi-entity-brand.md). Every one of these tables has a
  -- GLOBAL `UNIQUE (month_label)` rather than one scoped per entity+brand, so
  -- an upload under a second brand would find the first brand's rows and
  -- overwrite them in place, re-stamping their ids, with no error at all.
  -- Until the constraint itself is fixed (owner-gated), refuse the write
  -- instead of silently destroying the other dataset.
  SELECT t.month_label INTO v_conflict
  FROM public.tiv_forecast_tiv_actuals t
  WHERE t.month_label IN (SELECT jsonb_array_elements(p_tiv) ->> 'month_label')
    AND (t.entity_id, t.brand_id) IS DISTINCT FROM (p_entity_id, p_brand_id)
  LIMIT 1;

  IF v_conflict IS NOT NULL THEN
    RAISE EXCEPTION 'cross_scope_conflict: month % already belongs to a different entity/brand. Uploading here would overwrite that dataset.', v_conflict
      USING ERRCODE = '23505';
  END IF;

  -- Snapshot first, in the same transaction: if anything below fails, the
  -- snapshot rolls back with it and no orphan row is left behind.
  INSERT INTO public.tiv_forecast_snapshots (entity_id, brand_id, taken_by, reason, payload)
  VALUES (
    p_entity_id, p_brand_id, p_uploaded_by, 'pre-upload',
    jsonb_build_object(
      'tiv_actuals',   (SELECT coalesce(jsonb_agg(to_jsonb(x)), '[]'::jsonb) FROM public.tiv_forecast_tiv_actuals  x WHERE x.entity_id = p_entity_id AND x.brand_id = p_brand_id),
      'ptb_actuals',   (SELECT coalesce(jsonb_agg(to_jsonb(x)), '[]'::jsonb) FROM public.tiv_forecast_ptb_actuals  x WHERE x.entity_id = p_entity_id AND x.brand_id = p_brand_id),
      'al_actuals',    (SELECT coalesce(jsonb_agg(to_jsonb(x)), '[]'::jsonb) FROM public.tiv_forecast_al_actuals   x WHERE x.entity_id = p_entity_id AND x.brand_id = p_brand_id),
      'judgment_tiv',  (SELECT coalesce(jsonb_agg(to_jsonb(x)), '[]'::jsonb) FROM public.tiv_forecast_judgment_tiv x WHERE x.entity_id = p_entity_id AND x.brand_id = p_brand_id),
      'judgment_ptb',  (SELECT coalesce(jsonb_agg(to_jsonb(x)), '[]'::jsonb) FROM public.tiv_forecast_judgment_ptb x WHERE x.entity_id = p_entity_id AND x.brand_id = p_brand_id),
      'raw_data',      (SELECT coalesce(jsonb_agg(to_jsonb(x)), '[]'::jsonb) FROM public.tiv_forecast_raw_data     x WHERE x.entity_id = p_entity_id AND x.brand_id = p_brand_id),
      'model_params',  (SELECT coalesce(jsonb_agg(to_jsonb(x)), '[]'::jsonb) FROM public.tiv_forecast_model_params x WHERE x.entity_id = p_entity_id AND x.brand_id = p_brand_id)
    )
  )
  RETURNING id INTO v_snapshot_id;

  -- TIV actuals
  INSERT INTO public.tiv_forecast_tiv_actuals
    (month_label, year, month_num, month_index, bus_pvt, haulage, mav, tractor, tipper, icv_trucks, tiv_total, entity_id, brand_id)
  SELECT r.month_label, r.year, r.month_num, r.month_index, r.bus_pvt, r.haulage, r.mav, r.tractor, r.tipper, r.icv_trucks, r.tiv_total, p_entity_id, p_brand_id
  FROM jsonb_to_recordset(p_tiv) AS r(month_label text, year integer, month_num integer, month_index integer,
    bus_pvt numeric, haulage numeric, mav numeric, tractor numeric, tipper numeric, icv_trucks numeric, tiv_total numeric)
  ON CONFLICT (month_label) DO UPDATE SET
    year = excluded.year, month_num = excluded.month_num, month_index = excluded.month_index,
    bus_pvt = excluded.bus_pvt, haulage = excluded.haulage, mav = excluded.mav,
    tractor = excluded.tractor, tipper = excluded.tipper, icv_trucks = excluded.icv_trucks,
    tiv_total = excluded.tiv_total, entity_id = excluded.entity_id, brand_id = excluded.brand_id,
    updated_at = now();

  -- PTB actuals
  INSERT INTO public.tiv_forecast_ptb_actuals
    (month_label, year, month_num, month_index, bus_pvt, haulage, mav, tractor, tipper, icv_trucks, total_sale, entity_id, brand_id)
  SELECT r.month_label, r.year, r.month_num, r.month_index, r.bus_pvt, r.haulage, r.mav, r.tractor, r.tipper, r.icv_trucks, r.total_sale, p_entity_id, p_brand_id
  FROM jsonb_to_recordset(p_ptb) AS r(month_label text, year integer, month_num integer, month_index integer,
    bus_pvt numeric, haulage numeric, mav numeric, tractor numeric, tipper numeric, icv_trucks numeric, total_sale numeric)
  ON CONFLICT (month_label) DO UPDATE SET
    year = excluded.year, month_num = excluded.month_num, month_index = excluded.month_index,
    bus_pvt = excluded.bus_pvt, haulage = excluded.haulage, mav = excluded.mav,
    tractor = excluded.tractor, tipper = excluded.tipper, icv_trucks = excluded.icv_trucks,
    total_sale = excluded.total_sale, entity_id = excluded.entity_id, brand_id = excluded.brand_id,
    updated_at = now();

  -- AL actuals
  INSERT INTO public.tiv_forecast_al_actuals
    (month_label, month_index, bus_pvt, haulage, mav, tractor, tipper, icv_trucks, entity_id, brand_id)
  SELECT r.month_label, r.month_index, r.bus_pvt, r.haulage, r.mav, r.tractor, r.tipper, r.icv_trucks, p_entity_id, p_brand_id
  FROM jsonb_to_recordset(p_al) AS r(month_label text, month_index integer,
    bus_pvt numeric, haulage numeric, mav numeric, tractor numeric, tipper numeric, icv_trucks numeric)
  ON CONFLICT (month_label) DO UPDATE SET
    month_index = excluded.month_index,
    bus_pvt = excluded.bus_pvt, haulage = excluded.haulage, mav = excluded.mav,
    tractor = excluded.tractor, tipper = excluded.tipper, icv_trucks = excluded.icv_trucks,
    entity_id = excluded.entity_id, brand_id = excluded.brand_id, updated_at = now();

  -- Judgment TIV (nullable columns: a blank cell means nobody made a call)
  INSERT INTO public.tiv_forecast_judgment_tiv
    (month_label, bus_pvt, haulage, mav, tractor, tipper, icv_trucks, tiv_total, entity_id, brand_id)
  SELECT r.month_label, r.bus_pvt, r.haulage, r.mav, r.tractor, r.tipper, r.icv_trucks, r.tiv_total, p_entity_id, p_brand_id
  FROM jsonb_to_recordset(p_judg_tiv) AS r(month_label text,
    bus_pvt numeric, haulage numeric, mav numeric, tractor numeric, tipper numeric, icv_trucks numeric, tiv_total numeric)
  ON CONFLICT (month_label) DO UPDATE SET
    bus_pvt = excluded.bus_pvt, haulage = excluded.haulage, mav = excluded.mav,
    tractor = excluded.tractor, tipper = excluded.tipper, icv_trucks = excluded.icv_trucks,
    tiv_total = excluded.tiv_total, entity_id = excluded.entity_id, brand_id = excluded.brand_id;

  -- Judgment PTB
  INSERT INTO public.tiv_forecast_judgment_ptb
    (month_label, bus_pvt, haulage, mav, tractor, tipper, icv_trucks, total_sale, entity_id, brand_id)
  SELECT r.month_label, r.bus_pvt, r.haulage, r.mav, r.tractor, r.tipper, r.icv_trucks, r.total_sale, p_entity_id, p_brand_id
  FROM jsonb_to_recordset(p_judg_ptb) AS r(month_label text,
    bus_pvt numeric, haulage numeric, mav numeric, tractor numeric, tipper numeric, icv_trucks numeric, total_sale numeric)
  ON CONFLICT (month_label) DO UPDATE SET
    bus_pvt = excluded.bus_pvt, haulage = excluded.haulage, mav = excluded.mav,
    tractor = excluded.tractor, tipper = excluded.tipper, icv_trucks = excluded.icv_trucks,
    total_sale = excluded.total_sale, entity_id = excluded.entity_id, brand_id = excluded.brand_id;

  -- Raw data
  INSERT INTO public.tiv_forecast_raw_data (month_label, month_index, data, entity_id, brand_id)
  SELECT r.month_label, r.month_index, r.data, p_entity_id, p_brand_id
  FROM jsonb_to_recordset(p_raw) AS r(month_label text, month_index integer, data jsonb)
  ON CONFLICT (month_label) DO UPDATE SET
    month_index = excluded.month_index, data = excluded.data,
    entity_id = excluded.entity_id, brand_id = excluded.brand_id, updated_at = now();

  -- Model params: always a new row (the table keeps every training vintage).
  -- jsonb_populate_record fills only the keys present, so a v3 params object
  -- leaves the retired v2.1 columns NULL rather than failing. Columns are
  -- enumerated deliberately: `SELECT (…).*` would supply an explicit NULL for
  -- `id`, which overrides the sequence default and violates NOT NULL.
  INSERT INTO public.tiv_forecast_model_params (
    trained_at, last_data_month, total_months, seasonal_indices, hw_params, smly,
    yoy_capped, al_share_recent, ptb_share_recent, notes, model_backtest, yoy_sum,
    yoy_median, theta_params, tipper_norm_hw, tipper_norm_si, tipper_norm_smly,
    cap_scores, champion, yoy_t12, smly_plain, smly_robust, adapt_params, v3_method,
    entity_id, brand_id
  )
  SELECT
    coalesce(r.trained_at, now()), r.last_data_month, r.total_months, r.seasonal_indices,
    r.hw_params, r.smly, r.yoy_capped, r.al_share_recent, r.ptb_share_recent, r.notes,
    r.model_backtest, r.yoy_sum, r.yoy_median, r.theta_params, r.tipper_norm_hw,
    r.tipper_norm_si, r.tipper_norm_smly, r.cap_scores, r.champion, r.yoy_t12,
    r.smly_plain, r.smly_robust, r.adapt_params, r.v3_method,
    p_entity_id, p_brand_id
  FROM jsonb_populate_record(NULL::public.tiv_forecast_model_params, p_params) AS r;

  -- Upload history LAST but inside the same transaction, so it can no longer
  -- report failure for a committed upload -- nor succeed for a failed one.
  INSERT INTO public.tiv_forecast_upload_history
    (uploaded_by, uploader_name, file_name, months_loaded, last_data_month)
  VALUES (p_uploaded_by, p_uploader_name, p_file_name, coalesce(p_months_loaded, 0), p_last_data_month);

  RETURN jsonb_build_object(
    'ok', true,
    'snapshot_id', v_snapshot_id,
    'counts', jsonb_build_object(
      'tiv',      jsonb_array_length(p_tiv),
      'ptb',      jsonb_array_length(p_ptb),
      'al',       jsonb_array_length(p_al),
      'judg_tiv', jsonb_array_length(p_judg_tiv),
      'judg_ptb', jsonb_array_length(p_judg_ptb),
      'raw',      jsonb_array_length(p_raw)
    )
  );
END;
$fn$;

COMMENT ON FUNCTION public.tiv_upload_all IS
  'Atomic TIV upload: snapshot + six upserts + model params + history in ONE transaction. Called by the admin-tiv Edge Function with the service role. Refuses a month_label already owned by a different entity/brand (see docs/backlog/tiv-multi-entity-brand.md).';

-- Supabase grants EXECUTE to anon on function creation, so revoking from
-- PUBLIC alone is not enough -- it must come off anon AND authenticated.
-- Only the Edge Function's service-role client may call this.
REVOKE ALL ON FUNCTION public.tiv_upload_all(uuid, uuid, jsonb, jsonb, jsonb, jsonb, jsonb, jsonb, jsonb, uuid, text, text, integer, text) FROM PUBLIC;
REVOKE ALL ON FUNCTION public.tiv_upload_all(uuid, uuid, jsonb, jsonb, jsonb, jsonb, jsonb, jsonb, jsonb, uuid, text, text, integer, text) FROM anon;
REVOKE ALL ON FUNCTION public.tiv_upload_all(uuid, uuid, jsonb, jsonb, jsonb, jsonb, jsonb, jsonb, jsonb, uuid, text, text, integer, text) FROM authenticated;
