-- Phase 9.5 — Service Team: Outside-Workshop Job Tracker (v1)
-- ============================================================
-- Tracks outside-workshop vehicle work in four cases: {outside, ancillary} ×
-- {warranty, paid}. Replaces the manual PO process. Status tracking + PO/letter
-- PDF only (no money, no invoice metadata, no file uploads in v1).
--
-- Tables:  service_vendors (entity-scoped master), service_jobs, service_job_events (track log)
-- RPC:     create_service_job() — atomic fiscal-year PO numbering + insert + 'created' event + idempotency
-- Helper:  is_manager_or_above()
-- RLS:     entity + role scoped reads; writes go through the service-jobs Edge Function (service role)
-- Access:  access_rules seeded for service + accounts depts (all tiers) × both entities
--
-- Lifecycle: sequential spine (po_generated → work_completed → invoice_received)
-- + two parallel milestones (payment_done [accounts], settlement [warranty=mgr+/paid=accounts]).
-- Ancillary·Warranty is the exception: caps at work_completed, no invoice/payment,
-- settles via warranty_processed only.

begin;

-- ── 1. PO counter columns on entities (fiscal-year, Apr 1 rollover) ─────────
alter table public.entities
  add column if not exists po_serial_counter integer not null default 0,
  add column if not exists po_counter_fy     integer not null default 0;

-- ── 2. service_vendors — entity-scoped vendor master ───────────────────────
create table if not exists public.service_vendors (
  id          uuid        primary key default gen_random_uuid(),
  entity_id   uuid        not null references public.entities(id) on delete restrict,
  name        text        not null,
  oem         text,                                                            -- OEM/principal the vendor is an authorized dealer of (e.g. Bosch)
  is_authorized boolean   not null default false,                             -- true = authorized OEM dealer (ancillary work); false = general vendor (outside jobs)
  address     text,
  gstin       text,
  contact     text,
  is_active   boolean     not null default true,
  created_by  uuid        references public.users(id) on delete restrict,
  created_at  timestamptz not null default now()
);
create index if not exists service_vendors_entity_idx on public.service_vendors (entity_id, is_active);

-- ── 3. service_jobs — one row per job ──────────────────────────────────────
create table if not exists public.service_jobs (
  id                      uuid        primary key default gen_random_uuid(),
  po_number               text        unique not null,
  entity_id               uuid        not null references public.entities(id) on delete restrict,
  brand_id                uuid        references public.brands(id) on delete restrict,   -- nullable: optional metadata, not a visibility gate
  created_by              uuid        not null references public.users(id) on delete restrict,
  created_by_name         text        not null,                                          -- snapshot for the PO "generated by" line
  created_by_designation  text,                                                          -- snapshot: creator's designation for the PO footer
  vehicle_registration_no text        not null,
  job_type                text        not null check (job_type   in ('outside','ancillary')),
  repair_type             text        not null check (repair_type in ('warranty','paid')),
  job_description         text,
  vendor_id               uuid        references public.service_vendors(id) on delete restrict,
  vendor_name_snapshot    text,                                                          -- snapshots so vendor renames don't change issued POs
  vendor_gstin_snapshot   text,
  vendor_address_snapshot text,
  vendor_oem_snapshot     text,                                                          -- vendor's OEM/principal (e.g. Bosch) for the letter recipient
  ancillary_ref           text,                                                          -- added later, after the AL-portal warranty upload
  material_out_date       date        not null,                                          -- compulsory; defaults to today in the UI/EF
  material_return_date    date,                                                          -- auto-stamped when stage reaches work_completed
  -- Sequential spine
  stage                   text        not null default 'po_generated'
                            check (stage in ('po_generated','work_completed','invoice_received')),
  -- Parallel milestone: vendor payout
  payment_done_at         timestamptz,
  payment_done_by         uuid        references public.users(id) on delete restrict,
  -- Parallel milestone: settlement / recovery
  settlement_status       text        check (settlement_status in ('payment_received','warranty_processed')),
  settlement_at           timestamptz,
  settlement_by           uuid        references public.users(id) on delete restrict,
  -- Closure
  closed_at               timestamptz,
  final_outcome           text        check (final_outcome in ('completed','cancelled')),
  cancelled_at            timestamptz,
  cancelled_by            uuid        references public.users(id) on delete restrict,
  cancel_reason           text,
  -- Idempotency
  client_request_id       uuid,
  -- Customer name is common + mandatory for every job (vehicle owner).
  customer_name           text        not null,
  -- Ancillary·Warranty request-letter fields (nullable; required only for that case)
  chassis_no              text,
  engine_no               text,
  km_hrs                  text,
  date_of_sale            date,
  model                   text,
  make                    text,
  complaint_date          date,
  complaint               text,
  check_item              text,
  serial_no               text,
  qty                     text,
  created_at              timestamptz not null default now(),
  updated_at              timestamptz not null default now(),

  -- Date sanity: return cannot precede out (NULLs allowed)
  constraint service_jobs_material_dates_ck
    check (material_return_date is null or material_out_date is null
           or material_return_date >= material_out_date),

  -- Conditional letter-fields: Ancillary·Warranty REQUIRES the key letter fields.
  -- (The "no stray letter data on simple jobs" rule is enforced at creation in the
  -- Edge Function — not as a DB forbid — so that convert-to-paid on an AW job can
  -- retain its historical letter data without violating the constraint.)
  constraint service_jobs_letter_fields_ck check (
    not (job_type = 'ancillary' and repair_type = 'warranty')
    or (chassis_no is not null and engine_no is not null and check_item is not null)
  )
);

create unique index if not exists service_jobs_idempotency_idx
  on public.service_jobs (created_by, client_request_id)
  where client_request_id is not null;
create index if not exists service_jobs_entity_active_idx on public.service_jobs (entity_id, closed_at);
create index if not exists service_jobs_created_by_idx    on public.service_jobs (created_by);

-- ── 4. service_job_events — append-only track log ──────────────────────────
create table if not exists public.service_job_events (
  id                uuid        primary key default gen_random_uuid(),
  job_id            uuid        not null references public.service_jobs(id) on delete cascade,
  actor_id          uuid        not null references public.users(id) on delete restrict,
  event_type        text        not null check (event_type in
                       ('created','update','advance_stage','material_dates','payment_done',
                        'settlement','convert_to_paid','cancel','closed','undo')),
  from_value        text,
  to_value          text,
  note              text,
  reverted_event_id uuid        references public.service_job_events(id) on delete set null,
  created_at        timestamptz not null default now()
);
create index if not exists service_job_events_job_idx on public.service_job_events (job_id, created_at);

-- ── 5. updated_at trigger on service_jobs ──────────────────────────────────
create or replace function public.service_jobs_touch_updated_at()
returns trigger language plpgsql set search_path = public as $$
begin
  new.updated_at := now();
  return new;
end;
$$;
drop trigger if exists service_jobs_touch_updated_at_trg on public.service_jobs;
create trigger service_jobs_touch_updated_at_trg
  before update on public.service_jobs
  for each row execute function public.service_jobs_touch_updated_at();

-- ── 6. is_manager_or_above() helper ────────────────────────────────────────
create or replace function public.is_manager_or_above()
returns boolean language sql stable security definer set search_path = public as $$
  select exists (
    select 1 from public.users
    where id = auth.uid()
      and is_active = true
      and permission_level in ('manager','gm','admin')
  )
$$;
comment on function public.is_manager_or_above() is
  'Phase 9.5 — true iff active caller is manager/gm/admin. Used in service_jobs RLS.';

-- ── 7. create_service_job() — atomic numbering + insert + event + idempotency ──
-- Single transaction so a failed insert rolls back the consumed PO number (no gaps).
-- EF-only: the caller (service-role Edge Function) derives p_created_by / p_entity_id
-- from the verified JWT. Execute is revoked from authenticated to prevent a client
-- calling it directly with a forged p_created_by / p_entity_id.
create or replace function public.create_service_job(
  p_created_by        uuid,
  p_created_by_name   text,
  p_created_by_designation text,
  p_entity_id         uuid,
  p_client_request_id uuid,
  p_job               jsonb
)
returns table (id uuid, po_number text, idempotent boolean)
language plpgsql security definer set search_path = public as $$
declare
  v_counter  integer;
  v_fy_start integer;
  v_code     text;
  v_fy_str   text;
  v_po       text;
  v_id       uuid;
begin
  -- Idempotency pre-check: a re-submitted request returns the original row.
  if p_client_request_id is not null then
    select sj.id, sj.po_number into v_id, v_po
    from public.service_jobs sj
    where sj.created_by = p_created_by and sj.client_request_id = p_client_request_id;
    if found then
      return query select v_id, v_po, true;
      return;
    end if;
  end if;

  -- Fiscal-year PO number (Apr 1 rollover), row-locked counter update.
  v_fy_start := case
                  when extract(month from now()) >= 4 then extract(year from now())::integer
                  else extract(year from now())::integer - 1
                end;
  update public.entities
  set po_serial_counter = case when po_counter_fy = v_fy_start then po_serial_counter + 1 else 1 end,
      po_counter_fy     = v_fy_start
  where entities.id = p_entity_id
  returning po_serial_counter, code into v_counter, v_code;
  if not found then
    raise exception 'Entity % not found', p_entity_id;
  end if;
  v_fy_str := v_fy_start::text || '-' || lpad(((v_fy_start + 1) % 100)::text, 2, '0');
  v_po := 'PO-' || v_code || '-' || v_fy_str || '-' || lpad(v_counter::text, 4, '0');

  insert into public.service_jobs (
    po_number, entity_id, brand_id, created_by, created_by_name, created_by_designation,
    vehicle_registration_no, job_type, repair_type, job_description,
    vendor_id, vendor_name_snapshot, vendor_gstin_snapshot, vendor_address_snapshot, vendor_oem_snapshot,
    ancillary_ref, material_out_date, material_return_date, client_request_id,
    customer_name, chassis_no, engine_no, km_hrs, date_of_sale, model, make,
    complaint_date, complaint, check_item, serial_no, qty
  ) values (
    v_po, p_entity_id, (p_job->>'brand_id')::uuid, p_created_by, p_created_by_name, p_created_by_designation,
    p_job->>'vehicle_registration_no', p_job->>'job_type', p_job->>'repair_type', p_job->>'job_description',
    (p_job->>'vendor_id')::uuid, p_job->>'vendor_name_snapshot', p_job->>'vendor_gstin_snapshot', p_job->>'vendor_address_snapshot', p_job->>'vendor_oem_snapshot',
    p_job->>'ancillary_ref', (p_job->>'material_out_date')::date, (p_job->>'material_return_date')::date, p_client_request_id,
    p_job->>'customer_name', p_job->>'chassis_no', p_job->>'engine_no', p_job->>'km_hrs', (p_job->>'date_of_sale')::date, p_job->>'model', p_job->>'make',
    (p_job->>'complaint_date')::date, p_job->>'complaint', p_job->>'check_item', p_job->>'serial_no', p_job->>'qty'
  ) returning service_jobs.id into v_id;

  insert into public.service_job_events (job_id, actor_id, event_type, from_value, to_value)
  values (v_id, p_created_by, 'created', null, 'po_generated');

  return query select v_id, v_po, false;

exception
  when unique_violation then
    -- Idempotency race: another concurrent identical request won. Return its row.
    if p_client_request_id is not null then
      select sj.id, sj.po_number into v_id, v_po
      from public.service_jobs sj
      where sj.created_by = p_created_by and sj.client_request_id = p_client_request_id;
      if found then
        return query select v_id, v_po, true;
        return;
      end if;
    end if;
    raise;
end;
$$;

revoke all on function public.create_service_job(uuid, text, text, uuid, uuid, jsonb) from public;
revoke all on function public.create_service_job(uuid, text, text, uuid, uuid, jsonb) from authenticated;
grant execute on function public.create_service_job(uuid, text, text, uuid, uuid, jsonb) to service_role;

-- ── 8. RLS ─────────────────────────────────────────────────────────────────
alter table public.service_vendors    enable row level security;
alter table public.service_jobs        enable row level security;
alter table public.service_job_events  enable row level security;

-- service_vendors: entity-scoped read (admin bypass). Writes via EF (service role);
-- admin-only direct-write net.
drop policy if exists service_vendors_select on public.service_vendors;
create policy service_vendors_select on public.service_vendors
  for select to authenticated
  using (public.current_user_role() = 'admin' or entity_id = public.get_my_entity_id());

drop policy if exists service_vendors_admin_write on public.service_vendors;
create policy service_vendors_admin_write on public.service_vendors
  for all to authenticated
  using      (public.current_user_role() = 'admin')
  with check (public.current_user_role() = 'admin');

-- service_jobs: visible to admin, or to service/accounts dept + any manager+ in the same entity.
drop policy if exists service_jobs_select on public.service_jobs;
create policy service_jobs_select on public.service_jobs
  for select to authenticated
  using (
    public.current_user_role() = 'admin'
    or (
      entity_id = public.get_my_entity_id()
      and (public.current_user_role() in ('service','accounts') or public.is_manager_or_above())
    )
  );

drop policy if exists service_jobs_admin_write on public.service_jobs;
create policy service_jobs_admin_write on public.service_jobs
  for all to authenticated
  using      (public.current_user_role() = 'admin')
  with check (public.current_user_role() = 'admin');

-- service_job_events: readable iff the parent job is readable.
drop policy if exists service_job_events_select on public.service_job_events;
create policy service_job_events_select on public.service_job_events
  for select to authenticated
  using (
    exists (
      select 1 from public.service_jobs j
      where j.id = service_job_events.job_id
        and (
          public.current_user_role() = 'admin'
          or (
            j.entity_id = public.get_my_entity_id()
            and (public.current_user_role() in ('service','accounts') or public.is_manager_or_above())
          )
        )
    )
  );

-- RESTRICTIVE is_active gate (Phase 9d pattern) — deactivated users get nothing.
do $$
declare t text;
begin
  foreach t in array array['service_vendors','service_jobs','service_job_events'] loop
    execute format('drop policy if exists %I on public.%I', t || '_active_only', t);
    execute format($q$
      create policy %I on public.%I
        as restrictive for all to authenticated
        using (public.is_active_user()) with check (public.is_active_user())
    $q$, t || '_active_only', t);
  end loop;
end $$;

-- ── 9. access_rules — page visibility for /vendor-jobs ─────────────────────
-- service + accounts depts, all non-admin tiers (executive/manager/gm), × 2 entities = 12 rows.
-- Admin bypasses canAccess(). Per-action authority is enforced by the Edge Function;
-- access_rules only governs whether the page/nav is reachable. Other-department managers
-- are intentionally NOT seeded for visibility in v1 (add their tuple if needed).
-- Guard: a NULL dept/entity id below would silently create a wildcard rule.
do $$
begin
  if (select id from public.entities where code = 'PT')  is null
     or (select id from public.entities where code = 'PTB') is null
     or (select id from public.departments where code = 'service')  is null
     or (select id from public.departments where code = 'accounts') is null then
    raise exception 'Required entities (PT/PTB) or departments (service/accounts) missing — cannot seed access_rules safely';
  end if;
end $$;

with refs as (
  select
    (select id from public.entities    where code = 'PT')  as pt_id,
    (select id from public.entities    where code = 'PTB') as ptb_id,
    (select id from public.departments where code = 'service')  as service_id,
    (select id from public.departments where code = 'accounts') as accounts_id
),
new_rows(dept, tier, entity) as (values
  ('service','executive','PT'), ('service','manager','PT'), ('service','gm','PT'),
  ('service','executive','PTB'),('service','manager','PTB'),('service','gm','PTB'),
  ('accounts','executive','PT'),('accounts','manager','PT'),('accounts','gm','PT'),
  ('accounts','executive','PTB'),('accounts','manager','PTB'),('accounts','gm','PTB')
)
insert into public.access_rules (route, permission_level, entity_id, department_id, designation_id)
select
  '/vendor-jobs',
  r.tier,
  case r.entity when 'PT' then refs.pt_id when 'PTB' then refs.ptb_id end,
  case r.dept  when 'service' then refs.service_id when 'accounts' then refs.accounts_id end,
  null::uuid
from new_rows r cross join refs;

-- ── 10. Post-seed invariant ────────────────────────────────────────────────
do $$
declare n int;
begin
  select count(*) into n from public.access_rules where route = '/vendor-jobs';
  if n != 12 then raise exception '/service-jobs expected 12 access_rules rows, got %', n; end if;
end $$;

commit;

-- ============================================================
-- Rollback (manual — run interactively if 9.5 needs reverting)
-- ============================================================
--   delete from public.access_rules where route = '/vendor-jobs';
--   drop table if exists public.service_job_events;
--   drop table if exists public.service_jobs;
--   drop table if exists public.service_vendors;
--   drop function if exists public.create_service_job(uuid, text, text, uuid, uuid, jsonb);
--   drop function if exists public.is_manager_or_above();
--   drop function if exists public.service_jobs_touch_updated_at();
--   alter table public.entities drop column if exists po_serial_counter, drop column if exists po_counter_fy;
